# Nombre del workflow
name: potencia_flake8 + pytest

# Specifies the trigger for this workflow.
# Especifica el trigger que inicia el workflow
on:
  # Si hacemos push desde rama "potencia" -> inicia workflow
  push:
    branches: [ potencia] 
  # Si hacemos pull request hacia main -> inicia workflow  
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs
  flake8-lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    name: Lint
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3 # Download the repository
      - name: Set up Python 3.8 
        uses: actions/setup-python@v3 # Set up the Python environment
        with:
          python-version: "3.8"
      - name: Install dependencies # Install the dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run flake8 # Run the flake8 linter
        run: flake8 --ignore=E101,E191,E501,W191,W503,E302,E231,W292,W291,E226  --exclude=./src/, ./tests/
   